### ISSUE TITLE
Consider renaming sdk to `nitric_sdk` to fix readme

### ISSUE THREAD

**Issue by chimon2000** [nitrictech/dart-sdk#2]
### Issue
Currently when following the README, you will get an error trying to install nitric because nitric-sdk is not a valid name, but also dart_sdk is probably to generic.

### Steps

1. Follow getting started in README up to nitric dependency installation
2. Run `pub get`
3. Observe error attempting to install `nitric-sdk`

### Expected
Nitric installs correctly

### Output of `nitric info -o yaml`:

```yaml
{
  "os": "darwin",
  "arch": "arm64",
  "goVersion": "go1.19.13",
  "cliVersion": "1.33.6",
  "fabricVersion": "0.35.0",
  "containerRuntime": "docker",
  "containerRuntimeVersion": "platform:\n  name: Docker Engine - Community\ncomponents:\n- name: Engine\n  version: 25.0.2\n  details:\n    ApiVersion: \"1.44\"\n    Arch: arm64\n    BuildTime: \"2024-02-01T00:23:35.000000000+00:00\"\n    Experimental: \"false\"\n    GitCommit: fce6e0c\n    GoVersion: go1.21.6\n    KernelVersion: 6.5.13-orbstack-00121-ge428743e4e98\n    MinAPIVersion: \"1.24\"\n    Os: linux\n- name: containerd\n  version: v1.7.7\n  details:\n    GitCommit: 8c087663b0233f6e6e2f4515cee61d49f14746a8\n- name: runc\n  version: 1.1.9\n  details:\n    GitCommit: 82f18fe0e44a59034f3e1f45e475fa5636e539aa\n- name: docker-init\n  version: 0.19.0\n  details:\n    GitCommit: de40ad0\nversion: 25.0.2\napiversion: \"1.44\"\nminapiversion: \"1.24\"\ngitcommit: fce6e0c\ngoversion: go1.21.6\nos: linux\narch: arm64\nkernelversion: 6.5.13-orbstack-00121-ge428743e4e98\nexperimental: false\nbuildtime: \"2024-02-01T00:23:35.000000000+00:00\"\n",
  "detectedErrors": []
}
```

### Other info
n/a
